# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configwarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('diskwarning', models.CharField(max_length=50)),
                ('networkwarning', models.CharField(max_length=50)),
                ('networkwarningtime', models.CharField(max_length=50)),
                ('cpuwarning', models.CharField(max_length=50)),
                ('cpuwarningtime', models.CharField(max_length=50)),
                ('memorywarning', models.CharField(max_length=50)),
                ('memorywarningtime', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'configwarning',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hostsinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('system', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hostsinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userpass', models.CharField(max_length=50)),
                ('changepassword', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('trypass', models.CharField(blank=True, db_column='Trypass', max_length=50, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Whoerror',
            fields=[
                ('ip', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('mem', models.CharField(blank=True, max_length=50, null=True)),
                ('disk', models.CharField(blank=True, max_length=50, null=True)),
                ('newtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'whoerror',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wholesale',
            fields=[
                ('ip', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('mem', models.CharField(blank=True, max_length=50, null=True)),
                ('disk', models.CharField(blank=True, max_length=50, null=True)),
                ('newtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wholesale',
                'managed': False,
            },
        ),
    ]
